---

- name: Setup Tomcat and deploy an app
  hosts: tag_Role_Appserver
  become: true
  gather_facts: true
  user: ubuntu

  roles:

    - role: java
      java_type: Oracle
      java_version: "8"
      java_home: /usr/lib/jvm/java-{{ java_version }}-oracle
      # Whether Or Not To Install a script that will set JAVA_HOME environment variable
      java_home_install_script: True
      # Name of the script that will be placed into /etc/profile.d/
      java_home_script_name: java_home.sh
      java_tmp_storage: /tmp/java_install

    - role: tomcat

      tomcat_version: "8.0.38"
      tomcat_mirrors: http://archive.apache.org/dist/tomcat

      # Temporary Storage Directory
      tomcat_tmp_storage: /tmp/tomcat-ansible
      tomcat_user_name: tomcat
      tomcat_user_group: tomcat
      tomcat_user_home: /home/{{ tomcat_user_name }}
      tomcat_user_system: false

      tomcat_port_shutdown: 8005
      tomcat_port_connector: 8080
      tomcat_port_redirect: 8443
      tomcat_port_ajp: 8009

      tomcat_java_opts: ""
      tomcat_catalina_opts: ""

      tomcat_base_dir: /opt
      tomcat_catalina_home: "{{ tomcat_base_dir }}/tomcat"
      tomcat_instance_path: "{{ tomcat_base_dir }}/tomcat"

      tomcat_prefer_ipv4: true
      tomcat_override_uri_encoding: ""
      tomcat_prefer_urandom: true

      tomcat_instance: tomcat

      tomcat_roles:
        - manager
        - manager-gui
        - manager-script
        - manager-jmx
        - admin
        - admin-gui
        - admin-script

      # This Edits And Allows Ansible To Configure These
      # Otherwise it does a default install
      tomcat_configure: true
      tomcat_configure_configs: "{{ tomcat_configure }}"
      tomcat_configure_libs: "{{ tomcat_configure }}"
      tomcat_configure_webapps: "{{ tomcat_configure }}"

      # These copy files across and will use basename
      tomcat_extra_libs_path: ""
      tomcat_webapps_path: ""

      # Strings That Allow you to modify your
      # tomcat instance in a predictable fashion.
      tomcat_extra_global_naming_resources: ""
      tomcat_context_xml_header_extra: ""
      tomcat_context_xml_extra: ""

      # Disable or enable session persistence
      tomcat_disable_persistence_across_restarts: false

      # Custom Configuration Files
      # Use these to use custom xml files
      tomcat_use_custom_server_xml: false
      # tomcat_custom_server_xml: Path
      tomcat_use_custom_web_xml: false
      # tomcat_custom_web_xml: Path
      tomcat_use_custom_context_xml: false
      # tomcat_custom_context_xml: Path
      tomcat_use_custom_tomcat_users_xml: false
      # tomcat_custom_tomcat_users_xml: Path
      tomcat_use_custom_manager_context_xml: false
      # tomcat_custom_manager_context_xml: Path
    - role: deployment
